### ISSUE TITLE
Use `ghc-pkg update` in pacman hooks

### ISSUE THREAD

**Issue by nponeccop** [magthe/cblrepo#36]
Currently we `ghc-pkg unregister` then `register`. `ghc-pkg` has `update` option that does 2 actions in one step, possibly saving installaton time.

As there's no `runhaskell Setup update` option, `update.sh` can be generated from the generated `register.sh` just by replacing `register` with `update`.

**Comment by magthe** [comment]
I think the `register.sh` files do use `update` nowadays.
