### ISSUE TITLE
`-o` option of `cblrepo updatedb` is mandatory

### ISSUE THREAD

**Issue by nponeccop** [magthe/cblrepo#39]
`cblrepo convertdb` without further arguments operates silently and doesn't indicate a failure to find and convert the database.

I could only make it actually converting by supplying an `-o` argument. But `cblrepo convertdb -h` says that `-o` argument is optional.

**Comment by magthe** [comment]
It looks for a database called `cblrepo.db`, converts it and puts the result in `new-cblrepo.db`.

**Comment by nponeccop** [comment]
Indeed. I somehow only looked for `cblrepo*`. Sorry
