### ISSUE TITLE
arithmoi package cannot be patched

### ISSUE THREAD

**Issue by nponeccop** [magthe/cblrepo#40]
The reason seems to be that `cblrepo add` (and `cabal unpack` btw) convert line endings in `.cabal` file but `bsdtar` doesn't. 

Anyway here is a minimal example. Run it in an empty folder.

```bash
cblrepo add -g array,0.5.0.0 -g base,4.7.0.2 -g containers,0.5.5.1 \
     -g ghc-prim,0.3.1.0 -g integer-gmp,0.5.1.0 -d mtl,2.1.3.1,5 -d random,1.1,1
cblrepo add arithmoi,0.4.1.1 # fails because Hackage version requires random 1.0
mkdir patches
quilt new arithmoi.cabal
cabal unpack arithmoi
quilt add arithmoi-0.4.1.1/arithmoi.cabal
sed -i 's/< 1.1/< 1.2/g' arithmoi-0.4.1.1/arithmoi.cabal
quilt refresh
cblrepo add arithmoi,0.4.1.1 # succeeds
cblrepo pkgbuild --ghc-version=7.8.4 arithmoi
cd haskell-arithmoi
makepkg # fails with Hunk #1 FAILED at 38 (different line endings).
```
It is possible to prepare a patch that satisfies `makepkg`: just replace `cabal unpack` with 
```
wget http://hackage.haskell.org/package/arithmoi-0.4.1.1/arithmoi-0.4.1.1.tar.gz
bsdtar -xzvf arithmoi-0.4.1.1.tar.gz
```
but now `cblrepo add` fails with `Failed patching /tmp/cblrepo.0dE6Cj/arithmoi.cabal with patches/arithmoi.cabal`

**Comment by magthe** [comment]
I haven't verified this but I think you've hit what I think is a dark corner of Hackage.

The package `arithmoi` has had its Cabal file modified via Hackage (you can see that by the existance of the field `x-revision` at <http://hackage.haskell.org/package/arithmoi-0.4.1.1/arithmoi.cabal>).  I've noticed in the past that when the Cabal file is modified via Hackage it has DOS line endings.

As you probably know when a package is uploaded to Hackage the Cabal file is extracted and put into an index file (<http://hackage.haskell.org/packages/index.tar.gz>).  This index file is what *cblrepo* uses for all its operations.  Now if a package is uploaded with a Cabal file with Unix endings later on has its Cabal file modified via Hackage the line endings change.

*cblrepo* is not able to deal with this situation at the time.  This whole thing is something I only found out about a month ago, and I've been working on changes that improves the situation.  At the moment *cblrepo* can recognise that Hackage has been used to edit the Cabal file in the index.  Unfortunately it doesn't yet deal with it when creating `PKGBUILD`s yet.

A temporary workaround is to create patches for all stages:

1. `arithmoi.cabal` that applies to the Cabal in the index (i.e. the one with DOS line endings)
2. `arithmoi.pkgbuild` that disables the patching of the Cabal file in the package, this prevents the patch for the Cabal with DOS line endings to be applied to (and fail) to the Cabal file with the UNIX line endings
3. `arithmoi.source` that applies to the Cabal file in the package (i.e. the one with UNIX line endings)

I know this is ugly but it's what *cblrepo* has to offer at the time.

**Comment by nponeccop** [comment]
Ok, I investigated 6 ways to get a `.cabal` file from hackage, 

`cabal unpack`, `tar`, `bsdtar` and http://hackage.haskell.org/package/arithmoi-0.4.1.1/src/arithmoi.cabal (note the `src` part) all produce the same "correct" version.

The index tarball and http://hackage.haskell.org/package/arithmoi-0.4.1.1/arithmoi.cabal have the same "incorrect" version

**Comment by magthe** [comment]
Feel free to let me know if you have any ideas on how *cblrepo* can best deal with the situation.

**Comment by magthe** [comment]
I think this issue has been addressed as of https://github.com/magthe/cblrepo/commit/3dfca74df5d4a932a728d507ec8ed42bc4a7daf5
