### ISSUE TITLE
Constraint relaxation preserving pkgrel

### ISSUE THREAD

**Issue by nponeccop** [magthe/cblrepo#41]
It seems that `cblrepo` only patches during additions. Once a package is in `cblrepo.db` its constraints are set in stone and cannot be altered without losing `pkgrel`.

Here are minimal files to reproduce the issue:

supervisor-0.1.cabal:
```
name: supervisor
version: 0.1

library
    build-depends: extra ==0.1.*
```
extra-0.1.cabal:
```
name: extra
version: 0.1
```
extra-0.2.cabal:
```
name: extra
version: 0.2
```
First we install `extra-0.1` and `supervisor-0.1` and bump them so `pkgrels` are not 1:
```
$  cblrepo add -f extra-0.1.cabal -f supervisor-0.1.cabal
$ cblrepo bump --inclusive supervisor extra
$ cblrepo list
extra  0.1-2
supervisor  0.1-2
```
Now `extra-0.2` is out, and it turns out that the constraint in `supervisor-0.1` cabal is superficial as it is still compatible with `extra-0.2`. So I prepare a patch and put it to `patches/supervisor.cabal`:

```
Index: cblrepo-bug/supervisor-0.1.cabal
===================================================================
--- cblrepo-bug.orig/supervisor-0.1.cabal
+++ cblrepo-bug/supervisor-0.1.cabal
@@ -2,4 +2,4 @@ name: supervisor
 version: 0.1
 
 library
-    build-depends: extra ==0.1.*
+    build-depends: extra
```

Now I try adding `extra-0.2.cabal` and it fails:

```
$ cblrepo add -f extra-0.2.cabal 
Adding extra 0.2 would break:
  supervisor : extra ==0.1.*
```
If I add old unpatched `supervisor-0.1.cabal` along with `extra-0.2` it works because the patch is applied:

```
$ cblrepo add -f extra-0.2.cabal -f supervisor-0.1.cabal
```
But `pkgrel` of `supervisor`  is reset:
```
$ cblrepo list 
extra  0.2-1
supervisor  0.1-1
```
Is there a way to update to `extra-0.2` without losing pkgrel of `supervisor`? 

If it's not possible then one way to fix is to repatch all dependencies of the package being added during addition.

**Comment by magthe** [comment]
I've bumped into this issue myself a few times, but not often enough to make myself do something about it.

I suspect the issue with Hackage allowing updates to the Cabal file will increase the need of this sort of functionality, e.g. see <http://goo.gl/TQUDtX>.

Would you be kind enough to close this issue and create a new one with a more concise description of the functionality you are looking for (the **what**).  Possibly even some suggestions on how it could be realised (the **how**).  Also link to this issue so we have a good reason for doing it too (the **why**).
