### ISSUE TITLE
Cannot apply pkgbuild patch

### ISSUE THREAD

**Issue by tensor5** [magthe/cblrepo#43]
Hi,

I wrote a pkgbuild patch for `gitit` that adds two files to the package, `gitit.conf` and `gitit.service`:

    Index: haskell-happstack/haskell-gitit/PKGBUILD
    ===================================================================
    --- haskell-happstack.orig/haskell-gitit/PKGBUILD
    +++ haskell-happstack/haskell-gitit/PKGBUILD
    @@ -52,13 +52,22 @@ depends=("ghc=7.10.1-1"
              "haskell-uuid=1.3.10_0-7"
              "haskell-xml=1.3.14_0-80"
              "haskell-xss-sanitize=0.3.5.5_0-7"
    -         "haskell-zlib=0.5.4.2_0-76")
    +         "haskell-zlib=0.5.4.2_0-76"
    +         "mime-types")
    +optdepends=('git: Git filestore support'
    +            'darcs: Darcs filestore support'
    +            'mercurial: Mercurial filestore support'
    +            'postfix: notification emails support')
     options=('strip' 'staticlibs')
     source=("http://hackage.haskell.org/packages/archive/${_hkgname}/${_ver}/${_hkgname}-${_ver}.tar.gz"
    -        "original.cabal")
    +        "original.cabal"
    +        "gitit.conf"
    +        "gitit.service")
     install="${pkgname}.install"
     sha256sums=("c94271744ec5fe846e1b3994fc0349f4a38120a8d60618bedc1909367acf63a0"
    -            "e1f3c4b311d9e03575fd15ad2b00fa6b0eecffd634a976337846ba9048db8094")
    +            "e1f3c4b311d9e03575fd15ad2b00fa6b0eecffd634a976337846ba9048db8094"
    +            "d39af21ac72bbba302d76d3f0798665a4cedfc3fd8341987903682afbfe36286"
    +            "1b163ed91af72cc15eed9cbbf9309631417c5fe576cae582e4d268e3bbd42ee7")
     
     # PKGBUILD functions
     
    @@ -93,4 +102,10 @@ package() {
         runhaskell Setup copy --destdir="${pkgdir}"
         install -D -m644 "${_licensefile}" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
         rm -f "${pkgdir}/usr/share/doc/${pkgname}/${_licensefile}"
    +
    +    install -d -m755 "${pkgdir}/etc"
    +    install    -m644 "${srcdir}/gitit.conf" "${pkgdir}/etc"
    +
    +    install -d -m755 "${pkgdir}/usr/lib/systemd/system"
    +    install    -m644 "${srcdir}/gitit.service" "${pkgdir}/usr/lib/systemd/system"
     }

However `cblrepo pkgbuild` fails to generate the PKGBUILD with this patch:

    Failed patching /tmp/cblrepo.xs2Rim/PKGBUILD with /home/nicola/haskell-happstack/patches/gitit.pkgbuild

I think this has to do with `sha256sums` lines.
Is there a fix for this, or I should write a `gitit.source` patch, adding the two extra files to the source instead?

**Comment by magthe** [comment]
Yes, it sounds likely that it's the changes to the `sha256sums` line that causes it, but I'd have to run a few tests to confirm it.  However, the added files, where do you plan to keep them and ensure that they get copied into the package dir after generation?

There are 2 ways I deal with this sort of issue:

1. If the added files are small enough I simply create them from the PKGBUILD, e.g. using `HEREDOC'.
2. Otherwise I'll put them in the `<pkg>.source` patch.

**Comment by tensor5** [comment]
I was keeping them in the `haskell-gitit` directory, although it looks like a hack.
I didn't think about your option 1, but it sounds like a better idea! Thank you.
