### ISSUE TITLE
Feature request: <package>.install patch

### ISSUE THREAD

**Issue by tensor5** [magthe/cblrepo#46]
It was proposed at https://github.com/tensor5/haskell-happstack/issues/11 to run `gitit` with `systemd` without superuser privileges. For this purpose it would be necessary to create a `gitit` user and group, and add the `CAP_NET_BIND_SERVICE` capability to the executable `/usr/bin/gitit`. This would be done in `gitit.install`, thus it requires the ability to handle `<package>.install` patches, to a way similar to how it's done with `<package>.pkgbuild` patches.

Thanks

**Comment by magthe** [comment]
That's actually already supported.  Just add the patch in `patches/<package>.install`, e.g. `patches/zlib.install`, and it'll be picked up and applied when running `cblrepo pkgbuild`.

I'm guessing this means I really ought to look over the documentation ;)

**Comment by tensor5** [comment]
That's good news!

Yes the [README](https://github.com/magthe/cblrepo/blob/master/README.md#adding-patches-for-packages) only mentions cabal, source and pkgbuild pathces.
