### ISSUE TITLE
Error while calculating the source hashes

### ISSUE THREAD

**Issue by tensor5** [magthe/cblrepo#49]
Hi,

I'm trying to generate PKGBUILDs for my repo, but I get a sequence of:

```
makepkg: error while calculating the source hashes for <mypkg>
```

Does this have something to do with pacman 5?

Thanks

**Comment by magthe** [comment]
Yes, it does have to do with pacman 5. It's fixed in 40f5068dba7b87a7f0104d6b6d43581ea7556db3. I'll make a release with that change ASAP.
