### ISSUE TITLE
xrev required for distro packages

### ISSUE THREAD

**Issue by kyrias** [magthe/cblrepo#50]
The following example command from the README doesn't work anymore, because it requires xrev to be specified.  Shouldn't xrev really be optional when there might not necessarily be one, or should the README be changed?

```
$ cblrepo add -d xmonad-contrib,0.10,1 -d zlib,0.5.3.1,2.1
```

**Comment by kyrias** [comment]
https://github.com/magthe/cblrepo/commit/fa351b2b4786250a828ea4274c0052935f8c4a2b seems to imply that not having one is no longer supported, so I guess I'll have to add an xrev of 0 to the packages that doesn't have one.

**Comment by magthe** [comment]
Hmm, yes. I'll modify the README to make that a little clearer.
