### ISSUE TITLE
GHC pkg versions should be considered for `cblrepo upgrades`

### ISSUE THREAD

**Issue by felixonmars** [magthe/cblrepo#52]
Currently I have added Cabal==1.24.0.0 as GHC pkg in cblrepo.db, but cabal-install 1.24.0.2 appears in `cblrepo upgrades` and I think it shouldn't.

The definition in cblrepo.db:
`["Cabal",{"GhcPkg":{"gpVersion":"1.24.0.0"}}]`

The constraint in `cabal-install/1.24.0.2/cabal-install.cabal`:
`Cabal      >= 1.24.2 && < 1.25,`

And the output of `cblrepo upgrades` includes:
`cabal-install: 1.24.0.0:x2 (1.24.0.2:x0)`

**Comment by magthe** [comment]
Currently `cblrepo upgrades` answers the questions *what packages are available in newer versions than currently in `cblrepo.db`?* It's a question that is very easy to answer, and it's, at least in my opinion, not overlapping with to the question answered by `cblrepo add` (*can the following packages, and versions, be added?*).

Your request would change the question to *what package are available in newer versions than currently in `cblrepo.db`, and doesn't require upgrading any `GhcPkg`?* It introduces an overlap with `cblrepo add` and it also complicates providing the answer considerably (transitivity is required as well as considering new dependencies of dependencies).

**Comment by felixonmars** [comment]
I see. I somehow mixed up the two actions and thought `cblrepo upgrades` would give me which packages are *safe* to upgrade.

I'll update my script to use another `cblrepo add` call for that. Thanks!

**Comment by magthe** [comment]
Hmm, don't be so quick with closing. The fact that you mixed up the two actions might suggest that there is a communication problem here:

- should the command be renamed, maybe something like `clbrepo new-pkgs` is better?
- or should the documentation be improved?

**Comment by magthe** [comment]
OK, I'll go ahead and close this then.
