### ISSUE TITLE
`testing` flag was set for xmonad-0.12 by default

### ISSUE THREAD

**Issue by felixonmars** [magthe/cblrepo#54]
In the cabal file, flag `testing` defaults to `False`:

```
flag testing
    description: Testing mode, only build minimal components
    default: False
```

But when I use `cblrepo add xmonad,0.12`, it was set to True by default. Is there something I miss that made cblrepo change the flag?

**Comment by magthe** [comment]
What you are seeing is due to the behaviour of Cabal, it will flip flags when needed ([see here](https://www.haskell.org/cabal/users-guide/developing-packages.html#configuration-flags)). The way to prevent this is to add `manual: True` to the flag declaration.
