### ISSUE TITLE
cblrepo does not add `install` option to PKGBUILD

### ISSUE THREAD

**Issue by shtrom** [magthe/cblrepo#57]
I am working in archhaskell/habs, trying to add a few packages.

Rebuilding every package in the docker container, I repeatedly runs into the following sort of issue:
```
:: Proceed with installation? [Y/n]
:: Retrieving packages...
 haskell-extensible-excepti...    31.2 KiB  0.00B/s 00:00 [###############################] 100%
[...]
:: Processing package changes...
(1/2) installing haskell-extensible-exceptions            [###############################] 100%
[...]
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading alsa-core-0.5.0.1.tar.gz...
[...]
  -> Found original.cabal
==> Validating source files with sha256sums...
    alsa-core-0.5.0.1.tar.gz ... Passed
    original.cabal ... Passed
==> Extracting sources...
  -> Extracting alsa-core-0.5.0.1.tar.gz with bsdtar
bsdtar: Failed to set default locale
==> Starting prepare()...
==> Starting build()...
Configuring alsa-core-0.5.0.1...
Setup: Encountered missing dependencies:
extensible-exceptions >=0.1.1 && <0.2
==> ERROR: A failure occurred in build().
    Aborting...
*** ERROR: Trapped ERR, something went very wrong.
```

In this example, despite `extensible-exceptions` having been installed from a freshly built package, the next package build can't find it. I can work around the issue by restarting the container and manually running the `register.sh` script for that package, after which the build for that package succeeds, only to fail on the next similar issue.

```
$ docker start blissful_mcnulty
$ docker exec -it blissful_mcnulty sudo bash -x /usr/share/haskell/haskell-extensible-exceptions/register.sh
$ docker attach blissful_mcnulty
==> Finished making: haskell-alsa-core 0.5.0.1.x0-252 (Sat Feb 17 04:44:01 UTC 2018)                                                                                                             
==> Extracting database to a temporary location...                                                                                                                                               
bsdtar: Failed to set default locale                                                                                                                                                             
==> Extracting database to a temporary location...                                                                                                                                               
bsdtar: Failed to set default locale                                                                                                                                                             
==> Adding package 'haskell-alsa-core-0.5.0.1.x0-252-x86_64.pkg.tar.xz'     
```

Digging down, I can see that `haskell-extensible-exceptions` (created with `cblrepo pkgbuild extensible-exceptions`) has a `haskell-extensible-exceptions.install` which should call the `register.sh` script properly in the `post_install` hook. However, the `PKGBUILD` for this module never mentions the `install` script, which is therefore ignored.

This seems to be an issue with `cblrepo`, which fails to add this `install` section to the `PKGBUILD`.

**Comment by shtrom** [comment]
Ah... I was using `cblrepo` from the standard repos (`cblrepo 0.24.0-62`), replacing it with ` cblrepo-0.24.0.x0-11-x86_64` and recreating the `PKGBUILD`s fixed the issue.

I'm curious why, though, as it seems to be a similar version 🤔 .

**Comment by magthe** [comment]
I don't know why that would ever happen, it is indeed very strange!

However, since it isn't _our_ package that is broken I'll close this issue :)
